In [5]:
import pandas as pd
data = pd.read_csv('../data/house_raw.csv')
data

       housing_age  income  bedrooms  households      rooms  house_value
0               23  6.7770  0.141112    2.442244   8.103960       500000
1               49  6.0199  0.160984    2.726688   5.752412       500000
2               35  5.1155  0.249061    1.902676   3.888078       500000
3               32  4.7109  0.231383    1.913669   4.508393       500000
4               21  4.5625  0.255583    3.092664   4.667954       500000
...            ...     ...       ...         ...        ...          ...
17909           33  2.6750  0.246622    3.428571   4.698413        22500
17910           39  2.3667  0.340771    1.876812   3.572464        17500
17911           19  2.1000  0.386107    2.987805   3.774390        14999
17912           16  1.6607  0.286275    2.236842   6.710526        14999
17913           36  0.5360  0.285714    2.250000  12.250000        14999

[17914 rows x 6 columns]

In [7]:
x = data[data.columns[0:5]]
y = data['house_value']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, X_test, y_train, Y_test = train